import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { withAuthenticator } from '@aws-amplify/ui-react';
import { useEffect, useState } from 'react';
import '@aws-amplify/ui-react/styles.css';
import { Auth } from 'aws-amplify';

const Home: NextPage = () => {
  const [currUser, setCurrUser] = useState<any>()

  useEffect(() =>{
    const getCurrentUser = async () => {
      const data = await Auth.currentSession()
      let idToken = data.getIdToken();
      const { payload: {name, email}} = idToken
      setCurrUser({name, email})
    }

    getCurrentUser()
  }, [currUser])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Hello {currUser?.name || currUser?.email}</p>
        {currUser && <button onClick={() => Auth.signOut()}>Sign Out</button>}
      </main>
    </div>
  )
}

export default withAuthenticator(Home)
